from __future__ import annotations

from pathlib import Path

from hypervisor.agent_describe import describe_agent


def test_describe_weather_agent_markdown():
    report = describe_agent("weather-map-agent.local")
    md = report.markdown
    assert "# Agent report: `weather-map-agent`" in md
    assert "contracts/agents/weather_map_agent.yaml" in md
    assert "domains/weather_map" in md
    assert "agents/generated/weather_map_agent" in md
    assert "Markpact" in md
    assert "read_weather_map" in md
    assert "generate_weather_map" in md
    assert "hypervisor run-agent weather-map-agent.local" in md
    assert report.data["contract_format"] == "yaml"
    assert report.data["markpact_in_readme"] is True


def test_describe_desktop_operator_contract():
    report = describe_agent("desktop-operator.local")
    md = report.markdown
    assert "agents/operators/desktop_operator.yaml" in md
    assert "hypervisor.operator_agent" in md or "operator YAML" in md
    assert "domains/desktop_ops" in md
    assert "browser" in md
    assert "Operator runtime package" in md
    assert report.data["contract_format"] == "operator_yaml"
    assert report.data["is_operator"] is True


def test_describe_invoices_agent_skill_examples():
    report = describe_agent("invoices-agent.local")
    md = report.markdown
    assert "invoice_id=demo-1" in md
    assert "place=Gdansk" not in md


def test_describe_dashboard_system_agent_architecture():
    report = describe_agent("hypervisor-dashboard.local")
    md = report.markdown
    assert "System agent package" in md
    assert "packages/* system agent" in md
    assert "agent_id=hypervisor-dashboard.local" in md or "agent_id=" in md
    assert "place=Gdansk" not in md
    assert ".egg-info" not in md


def test_describe_screenshot_analysis_custom_agent():
    report = describe_agent("screenshot-analysis-agent.local")
    md = report.markdown
    assert report.data["agent_kind"] == "custom"
    assert report.data["markpact_in_readme"] is False
    assert "Custom agent package" in md
    assert "agents/custom/screenshot_analysis_agent" in md
    assert "contracts/agents/screenshot_analysis_agent.yaml" in md
    assert "analyze_screenshot" in md
    assert "hand-written FastAPI routes" in md
    assert "no Resource Runtime proxy" in md
    assert "not regenerated by `resource-agent-factory`" in md
    assert "Business logic and agent-to-agent orchestration" in md
    assert "resource proxy" not in md
    assert "generated artifact" not in md
    assert "via Resource Runtime" not in md
    assert "http://localhost:8134/health" in md


def test_describe_weather_agent_has_health_uri():
    from hypervisor.deployment_registry.loader import load_deployment_registry

    deployment = next(
        item for item in load_deployment_registry().deployments if item.id == "weather-map-agent.local"
    )
    declared = deployment.declared
    port = int(declared.preferred_port) if declared and declared.preferred_port else 8101
    health_uri = (
        deployment.health_uri
        or (declared.health_uri if declared else None)
        or f"http://localhost:{port}/health"
    )
    card_uri = (
        deployment.card_uri
        or (declared.card_uri if declared else None)
        or f"http://localhost:{port}/.well-known/agent-card.json"
    )

    report = describe_agent("weather-map-agent.local")
    assert report.data["contract_path"] == "contracts/agents/weather_map_agent.yaml"
    md = report.markdown
    assert health_uri in md
    assert card_uri in md
    assert "a2a://weather-map-agent/.well-known/agent-card.json" not in md


def test_describe_agent_writes_file(tmp_path: Path):
    out = tmp_path / "weather-map-agent.local.md"
    report = describe_agent("weather-map-agent")
    written = report.write(out)
    assert written == out
    text = out.read_text(encoding="utf-8")
    assert "weather-map-agent" in text
    assert len(text) > 500
