flowchart TD
%% generated in 0.01s
    packages__nl2uri["packages.nl2uri<br/>18 funcs"]
    packages__resource_agent_factory["packages.resource-agent-factory<br/>20 funcs"]
    packages__resource_agent_hypervisor["packages.resource-agent-hypervisor<br/>144 funcs"]
    packages__uri3["packages.uri3<br/>57 funcs"]
    packages__resource_agent_hypervisor ==>|10| packages__resource_agent_factory
    packages__resource_agent_hypervisor ==>|6| packages__uri3
    packages__nl2uri -->|3| packages__resource_agent_hypervisor
    packages__nl2uri -->|2| packages__resource_agent_factory
    packages__uri3 -->|1| packages__resource_agent_factory
    packages__resource_agent_hypervisor -->|1| packages__nl2uri
    packages__nl2uri -->|1| packages__uri3
